### PR TITLE
Ability to upload spec files for further testing within an instance

### PR DESCRIPTION
**Pull request by ytsarev**
I use this functionality to upload serverspec test suite for further `verify`

### CODE REVIEW

**Comment by grubernaut** [comment]
This achieves the functionality required, but test-kitchen's busser already uploads spec tests to the test suite during a verify run. Are these tests just needed in a different location than where chef-busser places them?

**Comment by ytsarev** [comment]
The reason is that busser is *very* limited, I use my custom serverspec invocation described in Rakefile and using [shell verifier](https://github.com/higanworks/kitchen-verifier-shell) to call it. 
In fact, with such setup I completely got rid of dependency on busser and any other chef library

**Comment by grubernaut** [comment]
Are you using a version of test-kitchen higher than 1.4? After 1.4 it's no longer using chef to verify any spec tests

**Comment by grubernaut** [comment]
I like that you only add this command to the `run_command` list, if the config setting is set. 

:heart: and :dollar: for that :)

**Comment by ytsarev** [comment]
I know that 1.4 is not bound to chef dependencies anymore. It doesn't make busser better though :)

**Comment by grubernaut** [comment]
hahaha sounds good to me :)

**Comment by neillturner** [comment]
@ytsarev can you explain how you use kitchen-shell-verifer to improve things so i can learn new stuff and document for others. -)

**Comment by ytsarev** [comment]
@neillturner sure, i'm using structure like
```yaml
verifier:                                                                       
  name: shell                                                                   
  remote_exec: true                                                             
  command: |                                                                    
    sudo -s <<SERVERSPEC                                                        
    cd /opt/gdc/serverspec-core                                                 
    export SERVERSPEC_ENV=$EC2DATA_ENVIRONMENT                                  
    export SERVERSPEC_BACKEND=exec                                              
    serverspec junit=true tag=~skip_in_kitchen check:role:$EC2DATA_TYPE               
    SERVERSPEC
```

where `serverspec` is a wrapper around `rake` invocation.
We use pretty complex `Rakefile` similar to one in https://github.com/vincentbernat/serverspec-example.

So as you can see we such approach we can achieve flexibility of running same test suite both in test kitchen and actual, even production instances.

Beware: kitchen-shell-verifier is not yet merged into test-kitchen upstream so using separate gem is unavoidable so far

**Pull request merged**
