### PR TITLE
custom_post_apply_command implementation

### PR DESCRIPTION
**Pull request by ytsarev**

### CODE REVIEW

**Comment by ytsarev** [comment]
@neillturner you've made a prediction with your previous typo :)

**Comment by ytsarev** [comment]
do not merge it yet, it can spoil converge exit status

**Comment by ytsarev** [comment]
it is better now

**Comment by neillturner** [comment]
what is the custom_post_apply_trap?

**Comment by ytsarev** [comment]
@neillturner if to do it simple and sequential the `custom_post_apply_command` will hide the real exit status of `puppet apply` . If to put it under `exit` `trap` ( http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html) it will be always executed after `puppet apply` without tampering the main exit status (which is equal to result of `converge` action

**Pull request merged**
