### PR TITLE
support puppet_version when using collections

### PR DESCRIPTION
**Pull request by jrwesolo**
https://github.com/neillturner/kitchen-puppet/issues/106

* enable the use of puppet_version when using:
  `require_puppet_collections: true`

* simplify logic for `install_command_collections` depending on platform

* Apt and Yum installations are now equivalent. Apt left out the actual
  installation and left it purely to `custom_install_command`.

* When using puppet collections, the package name for puppet is actually
  `puppet-agent` instead of `puppet`.

### CODE REVIEW

**Comment by jrwesolo** [comment]
Example of this functionality:

```yaml
platforms:
  - name: centos-6
    driver_config:
      box: puppetlabs/centos-6.6-64-nocm
      box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    provisioner:
      puppet_version: 1.3.2
  - name: debian-7
    driver_config:
      box: puppetlabs/debian-7.8-64-nocm
      box_url: https://vagrantcloud.com/puppetlabs/boxes/debian-7.8-64-nocm
    provisioner:
      puppet_version: 1.3.4-1wheezy
```

**Comment by jrwesolo** [comment]
@neillturner Please let me know if I misinterpreted the code. It seems like the install logic between debian and redhat-based systems was functionally different when using puppet collections. I made them function the same now and I was able to test this on multiple platforms successfully.

**Comment by neillturner** [comment]
thanks for this.

**Comment by jrwesolo** [comment]
Thank you!

**Pull request merged**
