### PR TITLE
Support facter files

### PR DESCRIPTION
**Pull request by neillturner**
support specifying facter files including structured facts. geneate a facter file when install_custom_facts set to true. @grubernaut @ytsarev can you review.

### CODE REVIEW

**Comment by ytsarev** [comment]
This one is complex enough to create supporting rspec tests... Rubocop compliance is also required

**Comment by neillturner** [comment]
ok added extra tests and fixed compliance. so will do a few more tests and then ready to merge

**Comment by neillturner** [comment]
i've done testing and will merge in 2 day's time if no objections

**Comment by grubernaut** [comment]
:+1: can you perhaps squash these commits before merging?

**Comment by ytsarev** [comment]
Please rebase with master as it is not mergeable at the moment

**Pull request merged**
